# --- MAPPO specific parameters ---

action_selector: "continuous"
mask_before_softmax: False

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0003
hidden_dim: 128

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

agent_output_type: "continuous_u_std" # Continuous means and stds
learner: "ppo_c_learner"
entropy_coef: 0.001
use_rnn: False
standardise_returns: False
standardise_rewards: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "mappo_c"

t_max: 20050000
