env: "gymma"

env_args:
  key: null
  time_limit: 100
  pretrained_wrapper: null
  max_cycles: 100
  continuous_actions: False

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000